enum GamePhases {
  DAY_DISCUSSION = 'DAY_DISCUSSION',
  DAY_VOTE = 'DAY_VOTE',
  DAY_FINAL_STATEMENT = 'DAY_FINAL_STATEMENT',
  DAY_FINAL_VOTE = 'DAY_FINAL_VOTE',
  NIGHT_ACTION = 'NIGHT_ACTION',
}

export default GamePhases;
